// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCategories
    {
        public tbCategories()
        {
            tbSubCategories = new HashSet<tbSubCategories>();
        }

        public int cat_Id { get; set; }
        public string cat_Description { get; set; }
        public bool cat_Status { get; set; }
        public int cat_IdUserCreate { get; set; }
        public DateTime cat_DateCreate { get; set; }
        public int? cat_IdUserModified { get; set; }
        public DateTime? cat_DateModified { get; set; }

        public virtual ICollection<tbSubCategories> tbSubCategories { get; set; }
    }
}