// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCallBusiness
    {
        public tbCallBusiness()
        {
            tbCustomerCalls = new HashSet<tbCustomerCalls>();
        }

        public int cabu_Id { get; set; }
        public string cabu_Description { get; set; }
        public bool cacabu_Status { get; set; }

        public virtual ICollection<tbCustomerCalls> tbCustomerCalls { get; set; }
    }
}