// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbContacts
    {
        public tbContacts()
        {
            tbMeetingsDetails = new HashSet<tbMeetingsDetails>();
        }

        public int cont_Id { get; set; }
        public string cont_Name { get; set; }
        public string cont_LastName { get; set; }
        public string cont_Email { get; set; }
        public string cont_Phone { get; set; }
        public int occ_Id { get; set; }
        public int cus_Id { get; set; }
        public bool cont_Status { get; set; }
        public int cont_IdUserCreate { get; set; }
        public DateTime cont_DateCreate { get; set; }
        public int? cont_IdUserModified { get; set; }
        public DateTime? cont_DateModified { get; set; }

        public virtual tbCustomers cus { get; set; }
        public virtual tbOccupations occ { get; set; }
        public virtual ICollection<tbMeetingsDetails> tbMeetingsDetails { get; set; }
    }
}