// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCotizations
    {
        public tbCotizations()
        {
            tbCotizationsDetail = new HashSet<tbCotizationsDetail>();
            tbSaleOrders = new HashSet<tbSaleOrders>();
        }

        public int cot_Id { get; set; }
        public int cus_Id { get; set; }
        public DateTime cot_DateValidUntil { get; set; }
        public int? sta_Id { get; set; }
        public bool cot_Status { get; set; }
        public int cot_IdUserCreate { get; set; }
        public DateTime cot_DateCreate { get; set; }
        public int? cot_IdUserModified { get; set; }
        public DateTime? cot_DateModified { get; set; }

        public virtual tbCustomers cus { get; set; }
        public virtual tbStates sta { get; set; }
        public virtual ICollection<tbCotizationsDetail> tbCotizationsDetail { get; set; }
        public virtual ICollection<tbSaleOrders> tbSaleOrders { get; set; }
    }
}