// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCountries
    {
        public tbCountries()
        {
            tbDepartments = new HashSet<tbDepartments>();
        }

        public int cou_Id { get; set; }
        public string cou_Description { get; set; }
        public bool cou_Status { get; set; }
        public int? cou_IdUserCreate { get; set; }
        public DateTime? cou_DateCreate { get; set; }
        public int? cou_IdUserModified { get; set; }
        public DateTime? cou_DateModified { get; set; }

        public virtual ICollection<tbDepartments> tbDepartments { get; set; }
    }
}