// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbComponents
    {
        public tbComponents()
        {
            tbModules = new HashSet<tbModules>();
        }

        public int com_Id { get; set; }
        public string com_Description { get; set; }
        public bool com_Status { get; set; }

        public virtual ICollection<tbModules> tbModules { get; set; }
    }
}