// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCustomersFile
    {
        public int cfi_Id { get; set; }
        public string cfi_fileRoute { get; set; }
        public int? cus_Id { get; set; }
        public bool cfi_Status { get; set; }
        public int cfi_IdUserCreate { get; set; }
        public DateTime cfi_DateCreate { get; set; }
        public int? cfi_IdUserModified { get; set; }
        public DateTime? cfi_DateModified { get; set; }

        public virtual tbCustomers cus { get; set; }
    }
}