// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbEventLogType
    {
        public tbEventLogType()
        {
            tbEventLog = new HashSet<tbEventLog>();
        }

        public int etype_Id { get; set; }
        public string etype_Name { get; set; }

        public virtual ICollection<tbEventLog> tbEventLog { get; set; }
    }
}