// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbModuleItems
    {
        public tbModuleItems()
        {
            tbRoleModuleItems = new HashSet<tbRoleModuleItems>();
        }

        public int mit_Id { get; set; }
        public int mod_Id { get; set; }
        public string mit_Descripction { get; set; }
        public bool? mit_Status { get; set; }

        public virtual tbModules mod { get; set; }
        public virtual ICollection<tbRoleModuleItems> tbRoleModuleItems { get; set; }
    }
}