// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbModules
    {
        public tbModules()
        {
            tbModuleItems = new HashSet<tbModuleItems>();
        }

        public int mod_Id { get; set; }
        public int com_Id { get; set; }
        public string mod_Description { get; set; }
        public bool? mod_Status { get; set; }

        public virtual tbComponents com { get; set; }
        public virtual ICollection<tbModuleItems> tbModuleItems { get; set; }
    }
}