// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbMunicipalities
    {
        public tbMunicipalities()
        {
            tbCustomers = new HashSet<tbCustomers>();
            tbPersons = new HashSet<tbPersons>();
        }

        public int mun_Id { get; set; }
        public string mun_Code { get; set; }
        public string mun_Description { get; set; }
        public int dep_Id { get; set; }
        public bool mun_Status { get; set; }
        public int? mun_IdUserCreate { get; set; }
        public DateTime? mun_DateCreate { get; set; }
        public int? mun_IdUserModified { get; set; }
        public DateTime? mun_DateModified { get; set; }

        public virtual tbDepartments dep { get; set; }
        public virtual tbUsers mun_IdUserCreateNavigation { get; set; }
        public virtual tbUsers mun_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbCustomers> tbCustomers { get; set; }
        public virtual ICollection<tbPersons> tbPersons { get; set; }
    }
}