// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbOrderDetails
    {
        public int ode_Id { get; set; }
        public int ode_Amount { get; set; }
        public int? pro_Id { get; set; }
        public decimal ode_TotalPrice { get; set; }
        public int? sor_Id { get; set; }
        public bool ode_Status { get; set; }
        public int ode_IdUserCreate { get; set; }
        public DateTime ode_DateCreate { get; set; }
        public int? ode_IdUserModified { get; set; }
        public DateTime? ode_DateModified { get; set; }

        public virtual tbProducts pro { get; set; }
        public virtual tbSaleOrders sor { get; set; }
    }
}