// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbRoleModuleItems
    {
        public int rmi_Id { get; set; }
        public int mit_Id { get; set; }
        public int rol_Id { get; set; }

        public virtual tbModuleItems mit { get; set; }
        public virtual tbRoles rol { get; set; }
    }
}