// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbStates
    {
        public tbStates()
        {
            tbCotizations = new HashSet<tbCotizations>();
            tbSaleOrders = new HashSet<tbSaleOrders>();
        }

        public int sta_Id { get; set; }
        public string sta_Description { get; set; }
        public bool sta_Status { get; set; }
        public int sta_IdUserCreate { get; set; }
        public DateTime sta_DateCreate { get; set; }
        public int? sta_IdUserModified { get; set; }
        public DateTime? sta_DateModified { get; set; }

        public virtual ICollection<tbCotizations> tbCotizations { get; set; }
        public virtual ICollection<tbSaleOrders> tbSaleOrders { get; set; }
    }
}