// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbUnits
    {
        public tbUnits()
        {
            tbProducts = new HashSet<tbProducts>();
        }

        public int uni_Id { get; set; }
        public string uni_Description { get; set; }
        public string uni_Abrevitation { get; set; }
        public bool uni_Status { get; set; }
        public int uni_IdUserCreate { get; set; }
        public DateTime uni_DateCreate { get; set; }
        public int? uni_IdUserModified { get; set; }
        public DateTime? uni_DateModified { get; set; }

        public virtual ICollection<tbProducts> tbProducts { get; set; }
    }
}