// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCustomerNotes
    {
        public int cun_Id { get; set; }
        public string cun_Descripcion { get; set; }
        public DateTime cun_ExpirationDate { get; set; }
        public int pry_Id { get; set; }
        public string pry_Descripcion { get; set; }
        public int cus_Id { get; set; }
        public string cus_Name { get; set; }
        public string Status { get; set; }
        public int cun_IdUserCreate { get; set; }
        public string cun_UserNameCreate { get; set; }
        public DateTime cun_DateCreate { get; set; }
        public int? cun_IdUserModified { get; set; }
        public string cun_UserNameModified { get; set; }
        public DateTime? cun_DateModified { get; set; }
    }
}