// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbContacts_List
    {
        public int cont_Id { get; set; }
        public string cont_Name { get; set; }
        public string cont_LastName { get; set; }
        public string cont_Email { get; set; }
        public string cont_Phone { get; set; }
        public int? occ_Id { get; set; }
        public string occ_Description { get; set; }
        public int? cus_Id { get; set; }
        public string cus_Name { get; set; }
        public string Status { get; set; }
        public int cont_IdUserCreate { get; set; }
        public string usu_UserNameCreate { get; set; }
        public DateTime cont_DateCreate { get; set; }
        public int? cont_IdUserModified { get; set; }
        public string usu_UserNameModified { get; set; }
        public DateTime? cont_DateModified { get; set; }
    }
}