// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_Areas_List
    {
        public int are_Id { get; set; }
        public string are_Description { get; set; }
        public string Status { get; set; }
        public int? are_IdUserCreate { get; set; }
        public string usu_UserNameCreate { get; set; }
        public DateTime are_DateCreate { get; set; }
        public int? are_IdUserModified { get; set; }
        public string usu_UserNameModified { get; set; }
        public DateTime? are_DateModified { get; set; }
    }
}