// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCampaignDetails_List
    {
        public int cde_Id { get; set; }
        public int cus_Id { get; set; }
        public int cam_Id { get; set; }
        public string cam_Nombre { get; set; }
        public string cam_Descripcion { get; set; }
        public string cam_Html { get; set; }
        public bool? cam_Status { get; set; }
        public int? cam_IdUserCreate { get; set; }
        public string cus_Name { get; set; }
        public string cus_Email { get; set; }
        public string cus_Phone { get; set; }
        public int? cus_IdUserCreate { get; set; }
    }
}