// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCustomersFile_List
    {
        public int cfi_Id { get; set; }
        public string cfi_fileRoute { get; set; }
        public int? cus_Id { get; set; }
        public string cus_Name { get; set; }
        public string Status { get; set; }
        public DateTime cfi_DateCreate { get; set; }
    }
}