// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_UserPermits_SELECT
    {
        public string usu_UserName { get; set; }
        public string mit_Descripction { get; set; }
    }
}