// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCustomerCalls
    {
        public int cca_Id { get; set; }
        public int cca_CallType { get; set; }
        public string cati_Description { get; set; }
        public int cca_Business { get; set; }
        public string cabu_Description { get; set; }
        public DateTime cca_Date { get; set; }
        public string cca_StartTime { get; set; }
        public string cca_EndTime { get; set; }
        public int cca_Result { get; set; }
        public string caru_Description { get; set; }
        public int cus_Id { get; set; }
        public string cus_Name { get; set; }
        public string Status { get; set; }
        public int cca_IdUserCreate { get; set; }
        public string cca_UserNameCreate { get; set; }
        public DateTime cca_DateCreate { get; set; }
    }
}