// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_ScreensPerRole_List
    {
        public int rmi_Id { get; set; }
        public int mit_Id { get; set; }
        public int rol_Id { get; set; }
        public string rol_Description { get; set; }
        public string mit_Descripction { get; set; }
    }
}