// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCallBusiness_List
    {
        public int cabu_Id { get; set; }
        public string cabu_Description { get; set; }
        public bool cacabu_Status { get; set; }
    }
}