// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCallType_List
    {
        public int cati_Id { get; set; }
        public string cati_Description { get; set; }
        public bool cati_Status { get; set; }
    }
}