// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbModules_List
    {
        public int mod_Id { get; set; }
        public string mod_Description { get; set; }
        public int? com_Id { get; set; }
        public string com_Description { get; set; }
        public string Status { get; set; }
    }
}