// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Entities.Entities
{
    public partial class tbAccesos
    {
        public int acce_Id { get; set; }
        public int rol_Id { get; set; }
        public int pant_Id { get; set; }

        public virtual tbPantallas pant { get; set; }
        public virtual tbRoles rol { get; set; }
    }
}