// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbAccesos = new HashSet<tbAccesos>();
        }

        public int pant_Id { get; set; }
        public string pant_Nombre { get; set; }

        public virtual ICollection<tbAccesos> tbAccesos { get; set; }
    }
}