// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Entities.Entities
{
    public partial class tbEnfermo
    {
        public int enfer_Inscripcioon { get; set; }
        public string enfer_Apellido { get; set; }
        public string enfer_Direccion { get; set; }
        public DateTime? enfer_FechaNac { get; set; }
        public int enfer_NSS { get; set; }
        public int? planti_EmpleadoId { get; set; }

        public virtual tbPlantilla planti_Empleado { get; set; }
    }
}