// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Entities.Entities
{
    public partial class tbHospiltales
    {
        public tbHospiltales()
        {
            tbPlantilla = new HashSet<tbPlantilla>();
            tbSala = new HashSet<tbSala>();
        }

        public int hospi_Id { get; set; }
        public string hospi_Nombre { get; set; }
        public string hospi_Telefono { get; set; }

        public virtual ICollection<tbPlantilla> tbPlantilla { get; set; }
        public virtual ICollection<tbSala> tbSala { get; set; }
    }
}