// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbAccesos = new HashSet<tbAccesos>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int rol_Id { get; set; }
        public string rol_Nombre { get; set; }
        public string rol_Descripcion { get; set; }

        public virtual ICollection<tbAccesos> tbAccesos { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}