// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbAreas
    {
        public tbAreas()
        {
            tbEmployees = new HashSet<tbEmployees>();
        }

        public int are_Id { get; set; }
        public string are_Description { get; set; }
        public bool are_Status { get; set; }
        public int? are_IdUserCreate { get; set; }
        public DateTime are_DateCreate { get; set; }
        public int? are_IdUserModified { get; set; }
        public DateTime? are_DateModified { get; set; }

        public virtual ICollection<tbEmployees> tbEmployees { get; set; }
    }
}