// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCampaignDetails
    {
        public int cde_Id { get; set; }
        public int cus_Id { get; set; }
        public int cam_Id { get; set; }

        public virtual tbCampaign cam { get; set; }
        public virtual tbCustomers cus { get; set; }
    }
}