// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCotizationsDetail
    {
        public int code_Id { get; set; }
        public int code_Cantidad { get; set; }
        public int pro_Id { get; set; }
        public decimal code_TotalPrice { get; set; }
        public int cot_Id { get; set; }
        public bool code_Status { get; set; }
        public int code_IdUserCreate { get; set; }
        public DateTime code_DateCreate { get; set; }
        public int? code_IdUserModified { get; set; }
        public DateTime? code_DateModified { get; set; }

        public virtual tbCotizations cot { get; set; }
    }
}