// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCustomerCalls
    {
        public int cca_Id { get; set; }
        public int cca_CallType { get; set; }
        public int cca_Business { get; set; }
        public DateTime cca_Date { get; set; }
        public string cca_StartTime { get; set; }
        public string cca_EndTime { get; set; }
        public int cca_Result { get; set; }
        public int cus_Id { get; set; }
        public bool cca_Status { get; set; }
        public int cca_IdUserCreate { get; set; }
        public DateTime cca_DateCreate { get; set; }
        public int? cca_IdUserModified { get; set; }
        public DateTime? cca_DateModified { get; set; }

        public virtual tbCallBusiness cca_BusinessNavigation { get; set; }
        public virtual tbCallType cca_CallTypeNavigation { get; set; }
        public virtual tbCallResult cca_ResultNavigation { get; set; }
        public virtual tbCustomers cus { get; set; }
    }
}