// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbCustomers
    {
        public tbCustomers()
        {
            tbCampaignDetails = new HashSet<tbCampaignDetails>();
            tbContacts = new HashSet<tbContacts>();
            tbCotizations = new HashSet<tbCotizations>();
            tbCustomerCalls = new HashSet<tbCustomerCalls>();
            tbCustomerNotes = new HashSet<tbCustomerNotes>();
            tbCustomersFile = new HashSet<tbCustomersFile>();
            tbMarketingDetails = new HashSet<tbMarketingDetails>();
            tbMeetings = new HashSet<tbMeetings>();
            tbMeetingsDetails = new HashSet<tbMeetingsDetails>();
            tbSaleOrders = new HashSet<tbSaleOrders>();
        }

        public int cus_Id { get; set; }
        public int cus_AssignedUser { get; set; }
        public int tyCh_Id { get; set; }
        public string cus_Name { get; set; }
        public string cus_RTN { get; set; }
        public string cus_Address { get; set; }
        public int dep_Id { get; set; }
        public int mun_Id { get; set; }
        public string cus_Email { get; set; }
        public bool cus_Receive_email { get; set; }
        public string cus_Phone { get; set; }
        public string cus_AnotherPhone { get; set; }
        public bool cus_Status { get; set; }
        public bool cus_Active { get; set; }
        public int cus_IdUserCreate { get; set; }
        public DateTime cus_DateCreate { get; set; }
        public int? cus_IdUserModified { get; set; }
        public DateTime? cus_DateModified { get; set; }

        public virtual tbUsers cus_AssignedUserNavigation { get; set; }
        public virtual tbMunicipalities tbMunicipalities { get; set; }
        public virtual tbTypeChannels tyCh { get; set; }
        public virtual ICollection<tbCampaignDetails> tbCampaignDetails { get; set; }
        public virtual ICollection<tbContacts> tbContacts { get; set; }
        public virtual ICollection<tbCotizations> tbCotizations { get; set; }
        public virtual ICollection<tbCustomerCalls> tbCustomerCalls { get; set; }
        public virtual ICollection<tbCustomerNotes> tbCustomerNotes { get; set; }
        public virtual ICollection<tbCustomersFile> tbCustomersFile { get; set; }
        public virtual ICollection<tbMarketingDetails> tbMarketingDetails { get; set; }
        public virtual ICollection<tbMeetings> tbMeetings { get; set; }
        public virtual ICollection<tbMeetingsDetails> tbMeetingsDetails { get; set; }
        public virtual ICollection<tbSaleOrders> tbSaleOrders { get; set; }
    }
}