// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbDepartments
    {
        public tbDepartments()
        {
            tbMunicipalities = new HashSet<tbMunicipalities>();
            tbPersons = new HashSet<tbPersons>();
        }

        public int dep_Id { get; set; }
        public string dep_Code { get; set; }
        public string dep_Description { get; set; }
        public int cou_Id { get; set; }
        public bool dep_Status { get; set; }
        public int? dep_IdUserCreate { get; set; }
        public DateTime? dep_DateCreate { get; set; }
        public int? dep_IdUserModified { get; set; }
        public DateTime? dep_DateModified { get; set; }

        public virtual tbCountries cou { get; set; }
        public virtual tbUsers dep_IdUserCreateNavigation { get; set; }
        public virtual tbUsers dep_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbMunicipalities> tbMunicipalities { get; set; }
        public virtual ICollection<tbPersons> tbPersons { get; set; }
    }
}