// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbEmployees
    {
        public tbEmployees()
        {
            tbMeetingsDetails = new HashSet<tbMeetingsDetails>();
        }

        public int emp_Id { get; set; }
        public int per_Id { get; set; }
        public int are_Id { get; set; }
        public int occ_Id { get; set; }
        public bool emp_Status { get; set; }
        public int emp_IdUserCreate { get; set; }
        public DateTime emp_DateCreate { get; set; }
        public int? emp_IdUserModified { get; set; }
        public DateTime? emp_DateModified { get; set; }

        public virtual tbAreas are { get; set; }
        public virtual tbOccupations occ { get; set; }
        public virtual tbPersons per { get; set; }
        public virtual ICollection<tbMeetingsDetails> tbMeetingsDetails { get; set; }
    }
}