// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbMarketingHeaders
    {
        public tbMarketingHeaders()
        {
            tbMarketingDetails = new HashSet<tbMarketingDetails>();
        }

        public int mhe_Id { get; set; }
        public string mhe_Description { get; set; }
        public bool mhe_Status { get; set; }
        public int mhe_IdUserCreate { get; set; }
        public DateTime mhe_DateCreate { get; set; }
        public int? mhe_IdUserModified { get; set; }
        public DateTime? mhe_DateModified { get; set; }

        public virtual ICollection<tbMarketingDetails> tbMarketingDetails { get; set; }
    }
}