// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbMeetings
    {
        public tbMeetings()
        {
            tbMeetingsDetails = new HashSet<tbMeetingsDetails>();
        }

        public int met_Id { get; set; }
        public string met_Title { get; set; }
        public string met_MeetingLink { get; set; }
        public int cus_Id { get; set; }
        public DateTime met_Date { get; set; }
        public string met_StartTime { get; set; }
        public string met_EndTime { get; set; }
        public bool met_Status { get; set; }
        public int met_IdUserCreate { get; set; }
        public DateTime met_DateCreate { get; set; }
        public int? met_IdUserModified { get; set; }
        public DateTime? met_DateModified { get; set; }

        public virtual tbCustomers cus { get; set; }
        public virtual ICollection<tbMeetingsDetails> tbMeetingsDetails { get; set; }
    }
}