// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbPriorities
    {
        public tbPriorities()
        {
            tbCustomerNotes = new HashSet<tbCustomerNotes>();
        }

        public int pry_Id { get; set; }
        public string pry_Descripcion { get; set; }
        public bool pry_Status { get; set; }
        public int pry_IdUserCreate { get; set; }
        public DateTime pry_DateCreate { get; set; }
        public int? pry_IdUserModified { get; set; }
        public DateTime? pry_DateModified { get; set; }

        public virtual ICollection<tbCustomerNotes> tbCustomerNotes { get; set; }
    }
}