// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbRoleModuleItems = new HashSet<tbRoleModuleItems>();
            tbUsers = new HashSet<tbUsers>();
        }

        public int rol_Id { get; set; }
        public string rol_Description { get; set; }
        public bool rol_Status { get; set; }
        public int? rol_IdUserCreate { get; set; }
        public DateTime? rol_DateCreate { get; set; }
        public int? rol_IdUserModified { get; set; }
        public DateTime? rol_DateModified { get; set; }

        public virtual tbUsers rol_IdUserCreateNavigation { get; set; }
        public virtual tbUsers rol_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbRoleModuleItems> tbRoleModuleItems { get; set; }
        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}