// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbSaleOrders
    {
        public tbSaleOrders()
        {
            tbOrderDetails = new HashSet<tbOrderDetails>();
        }

        public int sor_Id { get; set; }
        public int cus_Id { get; set; }
        public int? cot_Id { get; set; }
        public int? sta_Id { get; set; }
        public bool sor_Status { get; set; }
        public int sor_IdUserCreate { get; set; }
        public DateTime sor_DateCreate { get; set; }
        public int? sor_IdUserModified { get; set; }
        public DateTime? sor_DateModified { get; set; }

        public virtual tbCotizations cot { get; set; }
        public virtual tbCustomers cus { get; set; }
        public virtual tbStates sta { get; set; }
        public virtual ICollection<tbOrderDetails> tbOrderDetails { get; set; }
    }
}