// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbSubCategories
    {
        public tbSubCategories()
        {
            tbProducts = new HashSet<tbProducts>();
        }

        public int scat_Id { get; set; }
        public string scat_Description { get; set; }
        public int cat_Id { get; set; }
        public bool scat_Status { get; set; }
        public int scat_IdUserCreate { get; set; }
        public DateTime scat_DateCreate { get; set; }
        public int? scat_IdUserModified { get; set; }
        public DateTime? scat_DateModified { get; set; }

        public virtual tbCategories cat { get; set; }
        public virtual ICollection<tbProducts> tbProducts { get; set; }
    }
}