// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbTypeChannels
    {
        public tbTypeChannels()
        {
            tbCustomers = new HashSet<tbCustomers>();
        }

        public int tyCh_Id { get; set; }
        public string tyCh_Description { get; set; }
        public bool tyCh_Status { get; set; }
        public int tyCh_IdUserCreate { get; set; }
        public DateTime tyCh_DateCreate { get; set; }
        public int? tyCh_IdUserModified { get; set; }
        public DateTime? tyCh_DateModified { get; set; }

        public virtual ICollection<tbCustomers> tbCustomers { get; set; }
    }
}