// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class tbUsers
    {
        public tbUsers()
        {
            Inverseusu_IdUserModifiedNavigation = new HashSet<tbUsers>();
            tbCustomers = new HashSet<tbCustomers>();
            tbDepartmentsdep_IdUserCreateNavigation = new HashSet<tbDepartments>();
            tbDepartmentsdep_IdUserModifiedNavigation = new HashSet<tbDepartments>();
            tbMunicipalitiesmun_IdUserCreateNavigation = new HashSet<tbMunicipalities>();
            tbMunicipalitiesmun_IdUserModifiedNavigation = new HashSet<tbMunicipalities>();
            tbPersons = new HashSet<tbPersons>();
            tbRolesrol_IdUserCreateNavigation = new HashSet<tbRoles>();
            tbRolesrol_IdUserModifiedNavigation = new HashSet<tbRoles>();
        }

        public int usu_Id { get; set; }
        public string usu_UserName { get; set; }
        public string usu_Password { get; set; }
        public string usu_PasswordSalt { get; set; }
        public string usu_Profile_picture { get; set; }
        public bool? usu_Temporal_Password { get; set; }
        public int? rol_Id { get; set; }
        public bool usu_Status { get; set; }
        public int Per_Id { get; set; }
        public int? usu_IdUserCreate { get; set; }
        public DateTime? usu_DateCreate { get; set; }
        public int? usu_IdUserModified { get; set; }
        public DateTime? usu_DateModified { get; set; }

        public virtual tbPersons Per { get; set; }
        public virtual tbRoles rol { get; set; }
        public virtual tbUsers usu_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbUsers> Inverseusu_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbCustomers> tbCustomers { get; set; }
        public virtual ICollection<tbDepartments> tbDepartmentsdep_IdUserCreateNavigation { get; set; }
        public virtual ICollection<tbDepartments> tbDepartmentsdep_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbMunicipalities> tbMunicipalitiesmun_IdUserCreateNavigation { get; set; }
        public virtual ICollection<tbMunicipalities> tbMunicipalitiesmun_IdUserModifiedNavigation { get; set; }
        public virtual ICollection<tbPersons> tbPersons { get; set; }
        public virtual ICollection<tbRoles> tbRolesrol_IdUserCreateNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrol_IdUserModifiedNavigation { get; set; }
    }
}