// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbPriorities_List
    {
        public int pry_Id { get; set; }
        public string pry_Descripcion { get; set; }
        public string Status { get; set; }
        public int pry_IdUserCreate { get; set; }
        public string pry_UserNameCreate { get; set; }
        public DateTime pry_DateCreate { get; set; }
        public int? pry_IdUserModified { get; set; }
        public string pry_UserNameModified { get; set; }
        public DateTime? pry_DateModified { get; set; }
    }
}