// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCallResult_List
    {
        public int caru_Id { get; set; }
        public string caru_Description { get; set; }
        public bool caru_Status { get; set; }
    }
}