// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbMeetings_List
    {
        public int met_Id { get; set; }
        public string met_Title { get; set; }
        public string met_MeetingLink { get; set; }
        public int cus_Id { get; set; }
        public string cus_Name { get; set; }
        public DateTime met_Date { get; set; }
        public string met_StartTime { get; set; }
        public string met_EndTime { get; set; }
        public string Status { get; set; }
        public int met_IdUserCreate { get; set; }
        public DateTime met_DateCreate { get; set; }
    }
}