// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbUsers_List
    {
        public int usu_Id { get; set; }
        public string usu_UserName { get; set; }
        public string usu_Password { get; set; }
        public string usu_Profile_picture { get; set; }
        public int? rol_Id { get; set; }
        public string rol_Description { get; set; }
        public int Per_Id { get; set; }
        public bool? usu_Temporal_Password { get; set; }
        public string per_PerName { get; set; }
        public string Status { get; set; }
        public bool usu_Status { get; set; }
        public int? usu_IdUserCreate { get; set; }
        public string usu_UserNameCreate { get; set; }
        public DateTime? usu_DateCreate { get; set; }
        public int? usu_IdUserModified { get; set; }
        public string usu_UserNameModified { get; set; }
        public DateTime? usu_DateModified { get; set; }
    }
}