// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbRoles_List
    {
        public int rol_Id { get; set; }
        public string rol_Description { get; set; }
        public string Status { get; set; }
        public int? rol_IdUserCreate { get; set; }
        public string usu_UserNameCreate { get; set; }
        public DateTime? rol_DateCreate { get; set; }
        public int? rol_IdUserModified { get; set; }
        public string usu_UserNameModified { get; set; }
        public DateTime? rol_DateModified { get; set; }
    }
}