// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbProducts_List
    {
        public int pro_Id { get; set; }
        public string pro_Description { get; set; }
        public decimal pro_PurchasePrice { get; set; }
        public decimal pro_SalesPrice { get; set; }
        public int? pro_Stock { get; set; }
        public decimal pro_ISV { get; set; }
        public int uni_Id { get; set; }
        public string uni_Description { get; set; }
        public string scat_Description { get; set; }
        public int scat_Id { get; set; }
        public string Status { get; set; }
        public int pro_IdUserCreate { get; set; }
        public string usu_UserNameCreate { get; set; }
        public DateTime pro_DateCreate { get; set; }
        public int? pro_IdUserModified { get; set; }
        public string usu_UserNameModified { get; set; }
        public DateTime? pro_DateModified { get; set; }
    }
}