// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbModulosPantallas_List
    {
        public int mit_Id { get; set; }
        public string mit_Descripction { get; set; }
        public int? mod_Id { get; set; }
        public string mod_Description { get; set; }
        public string Status { get; set; }
    }
}