// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbCustomers_tbEmployees_List
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
    }
}