// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AHM.Logistic.Smart.Entities.Entities
{
    public partial class View_tbDepartments_List
    {
        public int dep_Id { get; set; }
        public string dep_Code { get; set; }
        public string dep_Description { get; set; }
        public int? cou_Id { get; set; }
        public string cou_Description { get; set; }
        public string Status { get; set; }
        public int? dep_IdUserCreate { get; set; }
        public string usu_UserNameCreate { get; set; }
        public DateTime? dep_DateCreate { get; set; }
        public int? dep_IdUserModified { get; set; }
        public string usu_UserNameModified { get; set; }
        public DateTime? dep_DateModified { get; set; }
    }
}