// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Template.Entities.Entities;

#nullable disable

namespace Template.DataAccess.Context
{
    public partial class TEMPLATE_Context : DbContext
    {
        public TEMPLATE_Context()
        {
        }

        public TEMPLATE_Context(DbContextOptions<TEMPLATE_Context> options)
            : base(options)
        {
        }

        public virtual DbSet<View_Areas_List> View_Areas_List { get; set; }
        public virtual DbSet<tbAreas> tbAreas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<View_Areas_List>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("View_Areas_List", "Gral");

                entity.Property(e => e.Status)
                    .HasMaxLength(8)
                    .IsUnicode(false);

                entity.Property(e => e.are_DateCreate).HasColumnType("datetime");

                entity.Property(e => e.are_DateModified).HasColumnType("datetime");

                entity.Property(e => e.are_Id).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<tbAreas>(entity =>
            {
                entity.HasKey(e => e.are_Id)
                    .HasName("PK_Gral_tbAreas_are_Id");

                entity.ToTable("tbAreas", "Gral");

                entity.Property(e => e.are_DateCreate).HasColumnType("datetime");

                entity.Property(e => e.are_DateModified).HasColumnType("datetime");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}